paths:
  output_folder:
    data/generated_corpus # path to the output folder where the generated dataset will be saved

  data_dir:
    data/ # path to the data directory

datasets:
  output_name: generated_semcor_25_25 # output name for the generated dataset

model:
  name: facebook/bart-large # model name
  max_tokens_per_batch: 250


optimiser:
  learning_rate: 0.00001
  weight_decay: 0.01
  no_decay_params:
    - "bias"
    - "LayerNorm.weight"

generation_parameters:
  num_beams: 10 # beam size
  num_return_sequences: 3 # top k beams to consider
  early_stopping: True # early stopping for generation

wandb:
  project_name: generative-substitution
